### ISSUE TITLE
MARS-Seq transform failing

### ISSUE THREAD

**Issue by tantrev** [vals/umis#12]
As I'm still wrapping my head around umi's transform syntax, I thought I'd mention a MARS-Seq example that seems to fail with the current "transform.json" recipe.  Any of the .fastq files extracted from [this](http://dr.tl/12ee04) dataset's .sra files should replicate the issue.

**Comment by vals** [comment]
Hi, the the transform syntax is Python Regular Expressions with named groups.

To learn about regular expressions in general for matching substrings, I think there a number of tutorial online. (I can't really think if any in particular to recommend though)

Here is the documentation for Python regular expression, with the named groups: https://docs.python.org/2/library/re.html

Just some brief hints: When you match something inside a () in a regular expression, that is called a "group". In Python, you can give name to various groups and extract the matched values.

In the transformation function in this package, one regular expression looks at all four lines corresponding to a read in fastq file at once.

The MARS-seq data I've based the example transform on in the examples folder is based on the first MARS-seq publication, where the data was provided through the author's web site.

It is also available here: http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE54006

In this data, a read looks like this:

```
@HWI-ST808:140:H0L10ADXX:1:1101:1718:2:NNNNNN:CTACCA:CCTT
CGTCGAACCTTTCTGGCCTGGCTTGTTTGCCAAGGCTCTGGCCAATGTCAACATTGGG
+
?<8BAADDAFDBFEHGBBHHIIHHFIJIGGEGGJGFCEG0?DCHBB9CB4BBFEC;@=
```

For this data, it has already been somewhat preprocessed. In the header of the read there is both the cellular barcode and the UMI.

So the transform looks like this:

```
{
    "read1": "(?P<name>@.*).*:(?P<CB>.{6}):(?P<MB>.{4,8})\\n(?P<seq>.*)\\n\\+\\n(?P<qual>.*)\\n",
    "read2": null
}
```

Here the CB extracts the cell barcode, and the MB extracts the UMI.

It is very likely that the new data you want to look at have different structure of the reads, with e.g. the UMI in the sequence part rather than the header.

Hope this is helpful...
