### ISSUE TITLE
Transforms don't understand multiple UMIs

### ISSUE THREAD

**Issue by lbeltrame** [vals/umis#65]
Regexes work with `CB1` and `CB2`, but not with UMIs. As there are nowadays libraries with dual UMIs like IDT's, it might be worthwhile to support `UMI1` and `UMI2` in transforms.

**Comment by roryk** [comment]
Agreed-- not sure if you are up for implementing and a PR but happy to tag team on it if you are. I haven't been using dual UMIs at all.

**Comment by roryk** [comment]
It would be helpful if you could attach some reads with the dual index and the appropriate transform that we could add it to the tests as a way to start. Hope you are well, Luca.

**Comment by roryk** [comment]
Thanks so much Luca! I'll cut a new release so bioconda picks it up.

**Comment by lbeltrame** [comment]
I'll try to review `bamtag` today to see whether it works or not (my tests with bcbio indicate that it doesn't, but I need to dig deeper).

**Comment by asee-imagia** [comment]
Hi! Commit [d0fae67343c78fbfc4a40cab63d03e799bc208ae](https://github.com/vals/umis/commit/d0fae67343c78fbfc4a40cab63d03e799bc208ae) fixed the problem of detecting duplex UMIs in the read name for us. It was [merged into main](https://github.com/vals/umis/commit/b58c77f5f1e31e823e6b979a9e004323a916145f). Would it be possible to trigger a new release so that bioconda picks it up? Thank you!

**Comment by roryk** [comment]
@asee-imagia thanks so much for the ping! I released v1.0.9.
